export class Company 
{
    companyId:string;
    companyName:string;
    emailId:string;
    phone:string;
    password:string
    constructor(
        companyId:string,
        companyName:string,
        emailId:string,
        phone:string,
        password:string
    )
    {
        this.companyId=companyId;
        this.companyName=companyName;
        this.emailId=emailId;
        this.phone=phone;
        this.password=password;
    }
}
